INSERT INTO TEAM(ID, NAME) VALUES(1, 'Manchester United');
INSERT INTO TEAM(ID, NAME) VALUES(2, 'Barcelona');
INSERT INTO PLAYER(ID, FIRSTNAME, LASTNAME, TEAM_ID) VALUES(1, 'Paul', 'Pogba', 1);
INSERT INTO PLAYER(ID, FIRSTNAME, LASTNAME, TEAM_ID) VALUES(2, 'Antoine', 'Griezmann', 2);
